### PR TITLE
NEW: Workflow support

### PR DESCRIPTION
**Pull request by unclecheese**
This pull request adds event handlers that bind to workflow events for publish and unpublish to ensure that snapshots are created when content is published or unpublished via workflow actions.

### CODE REVIEW

**Comment by unclecheese** [comment]
Dependent on: https://github.com/symbiote/silverstripe-advancedworkflow/pull/442

**Comment by chillu** [comment]
@unclecheese Will this work with embargo/expiry? I assume it does, since that extension creates a `WorkflowPublishTargetJob`. 

Could you note the workflow compatibility in the README? Specifically calling out modules this has been tested with should also clarify that other modules might not work as expected.

**Comment by unclecheese** [comment]
Yeah the reason for the update to the job was to make it compatible Embargo/Expiry.

Will make that README update. 👍

**Review by NightJar — COMMENTED** [review]
The changes here seem good, but does the travis config also need updating in order to get the tests to pass?

Should a test be added to cover the workflow? I'm not sure, as it would make the suite very messy... but the code lives here so...???

**Pull request merged**
